import { BRAND_COLORS } from '@/lib/brand'
import { escapeLatex } from '@/lib/latex/templates'
import type { RenderedEntry, RenderedResume, RenderedSection } from './render'

/**
 * Rendered variant → LaTeX for the existing pipeline (latexonline.cc via
 * lib/latex). Two templates, both standard packages only:
 *   ats    single column, no colour, no tables/icons — parses cleanly
 *   brand  same structure with the lee brand tokens (lib/brand.ts)
 * Every user string goes through escapeLatex.
 */

const e = escapeLatex

function hex(color: string): string {
  return color.replace('#', '').toUpperCase()
}

function preamble(r: RenderedResume, compact: boolean): string {
  const margin = compact ? '0.6in' : '0.75in'
  const brand = r.template === 'brand'
  return [
    `\\documentclass[${compact ? '10pt' : '11pt'},a4paper]{article}`,
    `\\usepackage[margin=${margin}]{geometry}`,
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage{lmodern}',
    '\\usepackage{textcomp}',
    '\\usepackage[hidelinks]{hyperref}',
    '\\usepackage{enumitem}',
    brand ? '\\usepackage[table]{xcolor}' : '',
    brand ? `\\definecolor{leetile}{HTML}{${hex(BRAND_COLORS.tile)}}` : '',
    brand ? `\\definecolor{leeglyph}{HTML}{${hex(BRAND_COLORS.glyph)}}` : '',
    '\\pagestyle{empty}',
    '\\setlength{\\parindent}{0pt}',
    '\\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,topsep=2pt,parsep=0pt}',
    brand
      ? '\\newcommand{\\cvsection}[1]{\\vspace{7pt}{\\color{leetile}\\large\\bfseries #1}\\\\[-7pt]{\\color{leeglyph}\\rule{\\linewidth}{1.2pt}}\\vspace{1pt}}'
      : '\\newcommand{\\cvsection}[1]{\\vspace{6pt}{\\bfseries\\MakeUppercase{#1}}\\\\[-7pt]\\rule{\\linewidth}{0.4pt}\\vspace{1pt}}',
  ]
    .filter(Boolean)
    .join('\n')
}

function header(r: RenderedResume): string {
  const brand = r.template === 'brand'
  const contact = r.contact.map((c) => e(c.field === 'profile' || c.field === 'url' || c.field === 'email' ? c.value : `${c.label}: ${c.value}`))
  const name = brand ? `{\\color{leetile}\\Huge\\bfseries ${e(r.name)}}` : `{\\LARGE\\bfseries ${e(r.name)}}`
  return [
    '\\begin{center}',
    `  ${name}\\\\[3pt]`,
    `  {\\large ${e(r.headline)}}\\\\[3pt]`,
    `  {\\small ${contact.join(' \\textperiodcentered{} ')}}`,
    '\\end{center}',
  ].join('\n')
}

function entry(x: RenderedEntry): string {
  const right = [x.location, x.dates].filter(Boolean).map(e).join(' \\textperiodcentered{} ')
  const head = `\\textbf{${e(x.title)}}${x.subtitle ? ` --- ${e(x.subtitle)}` : ''}${right ? ` \\hfill {\\small ${right}}` : ''}`
  const stack = x.keywords.length > 0 ? `\\\\{\\small\\textit{${e(x.keywords.join(', '))}}}` : ''
  const bullets = x.bullets.length > 0 ? `\n\\begin{itemize}\n${x.bullets.map((b) => `  \\item ${e(b.text)}`).join('\n')}\n\\end{itemize}` : ''
  return `${head}${stack}${bullets}`
}

function section(s: RenderedSection): string {
  const body = [
    ...s.lines.map((l) => `${e(l)}\\par`),
    ...s.entries.map(entry),
  ].join('\n\\vspace{3pt}\n')
  return `\\cvsection{${e(s.label)}}\n${body}`
}

export function variantToLatex(r: RenderedResume, lengthTarget: 1 | 2): string {
  return [
    `%% Generated by lee from a résumé variant — edit the variant, not this file.`,
    preamble(r, lengthTarget === 1),
    '\\begin{document}',
    header(r),
    ...r.sections.map(section),
    '\\end{document}',
    '',
  ].join('\n')
}
