import {
  CLASSIC_PREAMBLE,
  classicHeader,
  classicLink,
  displayUrl,
  highlights,
  oneColEntry,
  twoColEntry,
} from '@/lib/latex/classic-layout'
import { escapeLatex as e } from '@/lib/latex/escape'
import type { ContactLine, RenderedEntry, RenderedResume, RenderedSection } from './render'

/**
 * Rendered variant → the "Classic" layout (lib/latex/classic-layout.ts).
 * Same data contract as the ats / brand templates: every string comes from
 * the fact-locked RenderedResume and goes through escapeLatex; links only
 * reach \href when their URL is safe. The photo (already gated by the
 * variant's Photo toggle, its region and an uploaded photo) sits at the top
 * right; without it the header takes the full width.
 */

const LINK_FIELDS = new Set<ContactLine['field']>(['url', 'profile'])

function contactItem(c: ContactLine): string {
  if (c.field === 'email') return classicLink(`mailto:${c.value}`, c.value)
  if (c.field === 'phone') return classicLink(`tel:${c.value.replace(/[^\d+]/g, '')}`, c.value)
  if (LINK_FIELDS.has(c.field)) return classicLink(c.value, displayUrl(c.value))
  if (c.field === 'location') return e(c.value)
  // Tie the label to its value so a wrapped contact line never splits them.
  return `${e(c.label)}:~${e(c.value)}`
}

/** Line 1: phone, email, location and other facts; line 2: links. */
function contactLines(contact: readonly ContactLine[]): string[][] {
  const order = (c: ContactLine): number => (c.field === 'phone' ? 0 : c.field === 'email' ? 1 : 2)
  const facts = contact.filter((c) => !LINK_FIELDS.has(c.field)).sort((a, b) => order(a) - order(b))
  const links = contact.filter((c) => LINK_FIELDS.has(c.field))
  return [facts.map(contactItem), links.map(contactItem)]
}

function workEntry(x: RenderedEntry): string {
  const where = [x.subtitle, x.location].filter(Boolean).map(e).join(', ')
  const left = `\\textbf{${e(x.title)}}${where ? ` \\\\\n    ${where}` : ''}`
  const head = twoColEntry(left, x.dates ? `\\textit{${e(x.dates)}}` : '')
  const body = highlights(x.bullets.map((b) => e(b.text)))
  return body ? `${head}\n\n\\vspace{0.08 cm}\n\n${body}` : head
}

function projectEntry(x: RenderedEntry): string {
  const name = x.subtitle ? `${e(x.title)} -- ${e(x.subtitle)}` : e(x.title)
  const right = [x.keywords.length > 0 ? e(x.keywords.join(', ')) : '', x.dates ? e(x.dates) : '']
    .filter(Boolean)
    .map((r) => `\\textit{${r}}`)
    .join(' \\\\ ')
  const head = twoColEntry(`\\textbf{${name}}`, right)
  const body = highlights(x.bullets.map((b) => e(b.text)))
  return body ? `${head}\n\n\\vspace{0.05 cm}\n\n${body}` : head
}

const DATE_PART = /^(?:(?:[A-Z][a-z]{2} )?\d{4})(?: – (?:(?:[A-Z][a-z]{2} )?\d{4}|Present))?$/

/**
 * Education / certificate lines are "A · B · dates" (render.ts). The date
 * goes to the right column; the first part is bold, the rest below it.
 */
function datedLine(line: string, key: RenderedSection['key']): string {
  const parts = line.split(' · ')
  const last = parts.at(-1) ?? ''
  const dated = parts.length > 1 && DATE_PART.test(last)
  const [first, ...rest] = dated ? parts.slice(0, -1) : parts
  const tail = rest.map(e).join(', ')
  const left =
    key === 'education'
      ? `\\textbf{${e(first ?? '')}}${tail ? ` \\\\\n    \\textit{${tail}}` : ''}`
      : `\\textbf{${e(first ?? '')}}${tail ? ` -- ${tail}` : ''}`
  return twoColEntry(left, dated ? e(last) : '')
}

function section(s: RenderedSection): string {
  const heading = `\\section{${e(s.label.toUpperCase())}}`
  if (s.key === 'work' || s.key === 'projects') {
    const gap = s.key === 'work' ? '0.14 cm' : '0.10 cm'
    const entries = s.entries.map(s.key === 'work' ? workEntry : projectEntry)
    return [heading, entries.join(`\n\n\\entrygap{${gap}}\n\n`)].join('\n\n')
  }
  const lines =
    s.key === 'education' || s.key === 'certificates'
      ? s.lines.map((l) => datedLine(l, s.key))
      : s.lines.map((l) => oneColEntry(e(l)))
  return [heading, lines.join('\n\n\\entrygap{0.05 cm}\n\n')].join('\n\n')
}

/** `photo` is the validated asset file name (lee-photo.jpg / .png) or null. */
export function classicVariantToLatex(r: RenderedResume, photo: string | null): string {
  const name = e(r.name)
  return [
    '%% Generated by lee from a résumé variant (Classic layout) — edit the variant, not this file.',
    CLASSIC_PREAMBLE,
    `\\hypersetup{pdftitle={${name}}, pdfauthor={${name}}}`,
    '',
    '\\begin{document}',
    '',
    '\\justifying',
    '\\sloppy',
    '',
    classicHeader({
      name: e(r.name.toUpperCase()),
      title: e(r.headline),
      contactLines: contactLines(r.contact),
      photo,
    }),
    '',
    ...r.sections.map((s) => `${section(s)}\n`),
    '\\end{document}',
    '',
  ].join('\n')
}
